version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
    restart: unless-stopped
    volumes:
      - ./database:/database
    entrypoint:
      - ./database/entrypoint.sh
